import { execFileSync } from "node:child_process";
import { readFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, relative } from "node:path";

interface GitTimestamps {
  createdAt: Date | null;
  updatedAt: Date | null;
}

const timestampCache = new Map<string, GitTimestamps>();
const repoRoot = fileURLToPath(new URL("../../", import.meta.url));

function isValidDate(value: Date | null): value is Date {
  return value instanceof Date && !Number.isNaN(value.getTime());
}

/**
 * Load pre-built timestamp manifest (generated by scripts/generate-git-timestamps.ts).
 * Returns null when the file does not exist (e.g. local dev without prebuild).
 */
let manifestLoaded = false;
let manifest: Record<string, { createdAt: string | null; updatedAt: string | null }> | null = null;

function loadManifest() {
  if (manifestLoaded) return manifest;
  manifestLoaded = true;
  try {
    const raw = readFileSync(join(repoRoot, "src", "gitlog", "git-timestamps.json"), "utf8");
    manifest = JSON.parse(raw);
  } catch {
    manifest = null;
  }
  return manifest;
}

function fromManifest(filePath: string): GitTimestamps | null {
  const m = loadManifest();
  if (!m) return null;

  const key = relative(repoRoot, filePath).replace(/\\/g, "/");
  const entry = m[key];
  if (!entry) return null;

  const createdAt = entry.createdAt ? new Date(entry.createdAt) : null;
  const updatedAt = entry.updatedAt ? new Date(entry.updatedAt) : null;

  return {
    createdAt: isValidDate(createdAt) ? createdAt : null,
    updatedAt: isValidDate(updatedAt) ? updatedAt : null,
  };
}

export function getGitTimestamps(file: string | URL): GitTimestamps {
  const filePath = typeof file === "string" ? file : fileURLToPath(file);
  const cached = timestampCache.get(filePath);

  if (cached) {
    return cached;
  }

  // 1. Try pre-built manifest (production)
  const fromJson = fromManifest(filePath);
  if (fromJson) {
    timestampCache.set(filePath, fromJson);
    return fromJson;
  }

  // 2. Live git log (development)
  let createdAt: Date | null = null;
  let updatedAt: Date | null = null;

  try {
    const gitLog = execFileSync("git", ["log", "--follow", "--format=%aI", "--", filePath], {
      cwd: repoRoot,
      encoding: "utf8",
    });
    const timestamps = gitLog
      .split(/\r?\n/)
      .map((item) => item.trim())
      .filter(Boolean);

    if (timestamps.length > 0) {
      updatedAt = new Date(timestamps[0]);
      createdAt = new Date(timestamps[timestamps.length - 1]);
    }
  } catch {
  }

  // 3. File stats fallback
  try {
    const stats = statSync(filePath);

    if (!isValidDate(createdAt)) {
      createdAt = stats.birthtime;
    }

    if (!isValidDate(updatedAt)) {
      updatedAt = stats.mtime;
    }
  } catch {
  }

  const result = {
    createdAt: isValidDate(createdAt) ? createdAt : null,
    updatedAt: isValidDate(updatedAt) ? updatedAt : null,
  } satisfies GitTimestamps;

  timestampCache.set(filePath, result);
  return result;
}
